In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [5]:
df["diagnosis"].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [6]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_test

array([[ 0.44831542,  0.93278832,  0.76153424, ...,  2.00572924,
         0.59723193,  0.98755908],
       [-1.21235259, -0.83616123, -1.22285548, ..., -0.93510196,
        -0.09100651, -0.10558021],
       [ 1.61285957,  0.68612205,  1.56832924, ...,  1.89390482,
        -0.20623909, -0.40938071],
       ...,
       [-0.4833199 , -1.00530382, -0.53870962, ..., -0.99040971,
        -0.94814749, -1.29962467],
       [ 0.56336677,  0.0988214 ,  0.51297618, ...,  0.58223456,
        -0.39250545, -1.07557181],
       [-0.22234976, -0.51901888, -0.28363201, ..., -0.25221741,
        -0.61981356, -0.4050407 ]], shape=(114, 30))

In [10]:
y_train

141    M
282    M
28     M
94     M
219    M
      ..
246    B
461    M
560    B
493    B
222    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_test

array([1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0])

## **Transforming `numpy array` to PyTorch `tensor`**

In [13]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [14]:
y_test_tensor

tensor([1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
        1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0])

In [15]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

## **Defining The Model**

In [28]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [22]:
knn = MySimpleNN(X_train_tensor)

In [23]:
knn.weights

tensor([[0.2194],
        [0.2141],
        [0.7748],
        [0.2106],
        [0.5010],
        [0.4357],
        [0.6188],
        [0.5648],
        [0.7082],
        [0.5725],
        [0.3397],
        [0.6574],
        [0.4816],
        [0.8071],
        [0.0137],
        [0.4428],
        [0.6582],
        [0.5109],
        [0.5638],
        [0.2900],
        [0.0195],
        [0.5849],
        [0.6065],
        [0.4093],
        [0.8190],
        [0.4114],
        [0.9826],
        [0.6555],
        [0.0232],
        [0.7250]], dtype=torch.float64, requires_grad=True)

In [33]:
learning_rate = 0.09
epochs = 60

## Training Pipeline

In [34]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred, y_train_tensor)

  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.584252196672461
Epoch: 2, Loss: 3.483403332655329
Epoch: 3, Loss: 3.3780921933421575
Epoch: 4, Loss: 3.267082261536145
Epoch: 5, Loss: 3.1541373380305457
Epoch: 6, Loss: 3.0367473973457964
Epoch: 7, Loss: 2.9178634679569218
Epoch: 8, Loss: 2.7959620349477303
Epoch: 9, Loss: 2.6699580633583513
Epoch: 10, Loss: 2.545989272404661
Epoch: 11, Loss: 2.4190410077203843
Epoch: 12, Loss: 2.290793888503871
Epoch: 13, Loss: 2.161441033895456
Epoch: 14, Loss: 2.0305247535821804
Epoch: 15, Loss: 1.9053330951256982
Epoch: 16, Loss: 1.786239412448747
Epoch: 17, Loss: 1.6711174655242953
Epoch: 18, Loss: 1.5639829599639572
Epoch: 19, Loss: 1.4626635020831231
Epoch: 20, Loss: 1.3667272963713424
Epoch: 21, Loss: 1.2811996998283732
Epoch: 22, Loss: 1.2063487218212436
Epoch: 23, Loss: 1.1420532278068587
Epoch: 24, Loss: 1.0877214382990164
Epoch: 25, Loss: 1.0423324596703811
Epoch: 26, Loss: 1.0046028194430856
Epoch: 27, Loss: 0.9731883526187236
Epoch: 28, Loss: 0.9468360935104281
Epoch: 2

In [35]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5947983860969543
