In [2]:
import torch
import torch.nn as nn

In [3]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.liner = nn.Linear(in_features=num_features, out_features=1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.liner(features)
        out = self.sigmoid(out)

        return out

In [4]:
## create dataset
features = torch.rand(10, 5)

model = Model(features.shape[1])

model(features) ## forward pass

tensor([[0.5436],
        [0.4979],
        [0.5093],
        [0.5599],
        [0.5617],
        [0.5756],
        [0.5034],
        [0.5423],
        [0.5595],
        [0.5291]], grad_fn=<SigmoidBackward0>)

In [5]:
## show the model weight
model.liner.weight

Parameter containing:
tensor([[ 0.3111,  0.2470, -0.1558, -0.2469,  0.2888]], requires_grad=True)

In [6]:
model.liner.bias

Parameter containing:
tensor([-0.0861], requires_grad=True)

In [7]:
from torchinfo import summary
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            6
├─Sigmoid: 1-2                           --
Total params: 6
Trainable params: 6
Non-trainable params: 0

## ***Build `NN` with hidden layer***

In [10]:
class MyNewModel(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.liner = nn.Linear(in_features=num_features, out_features=3)
        self.relu = nn.ReLU()
        self.hidden = nn.Linear(in_features=3, out_features=1)
        self.sigmoid = nn.Sigmoid()


    def forward(self, features):
        out = self.liner(features)
        out = self.relu(out)
        out = self.hidden(out)
        out = self.sigmoid(out)

        return out

In [11]:
## datset
features = torch.rand(50, 5)

modeln = MyNewModel(features.shape[1])
modeln(features)

tensor([[0.5204],
        [0.5326],
        [0.5559],
        [0.5381],
        [0.5316],
        [0.5204],
        [0.5549],
        [0.5204],
        [0.5405],
        [0.5281],
        [0.5362],
        [0.5217],
        [0.5328],
        [0.5443],
        [0.5470],
        [0.5208],
        [0.5433],
        [0.5213],
        [0.5408],
        [0.5268],
        [0.5204],
        [0.5204],
        [0.5367],
        [0.5414],
        [0.5206],
        [0.5277],
        [0.5229],
        [0.5509],
        [0.5305],
        [0.5204],
        [0.5204],
        [0.5223],
        [0.5204],
        [0.5204],
        [0.5204],
        [0.5204],
        [0.5337],
        [0.5237],
        [0.5204],
        [0.5229],
        [0.5414],
        [0.5204],
        [0.5294],
        [0.5219],
        [0.5321],
        [0.5193],
        [0.5381],
        [0.5324],
        [0.5204],
        [0.5563]], grad_fn=<SigmoidBackward0>)

In [12]:
modeln.liner.weight, modeln.hidden.weight, modeln.liner.bias

(Parameter containing:
 tensor([[ 0.0471,  0.2638,  0.2163, -0.1000,  0.0966],
         [ 0.1285,  0.4208, -0.1786,  0.2928,  0.1306],
         [ 0.1832, -0.1988,  0.0618,  0.3570, -0.1050]], requires_grad=True),
 Parameter containing:
 tensor([[-0.2507,  0.3959,  0.1051]], requires_grad=True),
 Parameter containing:
 tensor([-0.4028, -0.3016, -0.2235], requires_grad=True))

In [13]:
summary(modeln)

Layer (type:depth-idx)                   Param #
MyNewModel                               --
├─Linear: 1-1                            18
├─ReLU: 1-2                              --
├─Linear: 1-3                            4
├─Sigmoid: 1-4                           --
Total params: 22
Trainable params: 22
Non-trainable params: 0

In [14]:
## Use sequential

In [15]:
class MyNewModel(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(in_features=num_features, out_features=3),
            nn.ReLU(),
            nn.Linear(in_features=3, out_features=1),
            nn.Sigmoid()
        )


    def forward(self, features):
        out = self.network(features)

        return out