## **Pytorch Tensor**

In [3]:
import torch

In [4]:
print('tst line')

tst line


In [5]:
if torch.cuda.is_available():
    print("GPU is avilable")
    print(f"Using GPU: {torch.cuda.get_device_name(0)} ")
else:
    print("GPU not avilable")

GPU is avilable
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU 


## **Creating a Tenson**

In [9]:
## It's creating a tensor and showing the existing value of that memory.
empt_tensor = torch.empty(2, 3)
empt_tensor

tensor([[3.0178e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 5.1334e-10, 0.0000e+00]])

In [10]:
type(empt_tensor)

torch.Tensor

In [11]:
## creating tensor using zero value
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
## To get the same tensor into the 