## **Pytorch Tensor**

In [1]:
import torch

In [2]:
print('tst line')

tst line


In [3]:
if torch.cuda.is_available():
    print("GPU is avilable")
    print(f"Using GPU: {torch.cuda.get_device_name(0)} ")
else:
    print("GPU not avilable")

GPU is avilable
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU 


## **Creating a Tenson**

In [4]:
## It's creating a tensor and showing the existing value of that memory.
empt_tensor = torch.empty(2, 3)
empt_tensor

tensor([[1.3191e-21, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [5]:
type(empt_tensor)

torch.Tensor

In [6]:
## creating tensor using zero value
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [8]:
## To get the same tensor into the differents times
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.ones(4)

tensor([1., 1., 1., 1.])

## **Build my own custome Tensor**

In [10]:
torch.tensor(
    [
        [1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]
    ]
)

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [11]:
torch.arange(4, 10)

tensor([4, 5, 6, 7, 8, 9])

## **Identity matrix**

In [12]:
torch.eye(4, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [13]:
## matrix using specific numbers.
torch.full((3, 4), 8)

tensor([[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]])

## **Tensor Shapes Finding**

In [14]:
x = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [8, 9, 10]
    ]
)

In [15]:
x.shape

torch.Size([3, 3])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

## **Finding Tensor data types**

In [18]:
my_tensor = torch.tensor(
    [
        [1, 2, 3],
        [2, 3, 4]
    ]
)
my_tensor

tensor([[1, 2, 3],
        [2, 3, 4]])

In [19]:
my_tensor.dtype

torch.int64

In [20]:
my_tensor_int_16 = torch.tensor(
    [
        [1, 2, 3],
        [2, 3, 4]
    ],
    dtype = torch.int16
)
my_tensor_int_16.dtype

torch.int16

## Transfer one datatype to desier data type `.to` 

In [21]:
flot_data = my_tensor_int_16.to(torch.float64)
flot_data

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

## Math Operations

In [22]:
a = torch.rand(4, 4)
b = torch.rand(4, 4)
a, b


(tensor([[0.2627, 0.0428, 0.2080, 0.1180],
         [0.1217, 0.7356, 0.7118, 0.7876],
         [0.4183, 0.9014, 0.9969, 0.7565],
         [0.2239, 0.3023, 0.1784, 0.8238]]),
 tensor([[0.5557, 0.9770, 0.4440, 0.9478],
         [0.7445, 0.4892, 0.2426, 0.7003],
         [0.5277, 0.2472, 0.7909, 0.4235],
         [0.0169, 0.2209, 0.9535, 0.7064]]))

In [23]:
a.round()

tensor([[0., 0., 0., 0.],
        [0., 1., 1., 1.],
        [0., 1., 1., 1.],
        [0., 0., 0., 1.]])

In [24]:
a.floor()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
a

tensor([[0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876],
        [0.4183, 0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784, 0.8238]])

In [26]:
a.sum()

tensor(7.5899)

In [27]:
torch.sum(a, dim=0)

tensor([1.0266, 1.9822, 2.0951, 2.4860])

In [28]:
torch.sum(b, dim=1)

tensor([2.9246, 2.1766, 1.9892, 1.8977])

In [29]:
torch.median(a)

tensor(0.3023)

In [30]:
torch.argmax(a)

tensor(10)

In [31]:
a

tensor([[0.2627, 0.0428, 0.2080, 0.1180],
        [0.1217, 0.7356, 0.7118, 0.7876],
        [0.4183, 0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784, 0.8238]])

In [32]:
## Matrix Operations

In [33]:
c = torch.randint(low=5, high=10, size=(3, 3))
d = torch.randint(low=1, high=4, size=(3, 3))
c, d

(tensor([[9, 5, 5],
         [7, 5, 9],
         [9, 7, 5]]),
 tensor([[1, 1, 2],
         [1, 1, 1],
         [3, 3, 3]]))

In [34]:
torch.matmul(c, d)

tensor([[29, 29, 38],
        [39, 39, 46],
        [31, 31, 40]])

In [35]:
## dot products
vector1 = torch.tensor(
    [1, 2]
)
vector2 = torch.tensor(
    [3, 4]
)
torch.matmul(vector1, vector2)

tensor(11)

In [36]:
torch.dot(vector1, vector2)

tensor(11)

In [37]:
c

tensor([[9, 5, 5],
        [7, 5, 9],
        [9, 7, 5]])

## A matrix f has 2 dimensions:

- dim 0 → rows

- dim 1 → columns

**👉 swap rows (0) with columns (1)**

In [38]:
torch.transpose(c, 0, 1)

tensor([[9, 7, 9],
        [5, 5, 7],
        [5, 9, 5]])

## **Spatial Functions**

In [39]:
k = torch.randint(size=(2, 3), high=15, low=4, dtype=torch.float32)
k

tensor([[13.,  6.,  4.],
        [10., 11.,  4.]])

In [40]:
torch.log(k)

tensor([[2.5649, 1.7918, 1.3863],
        [2.3026, 2.3979, 1.3863]])

In [41]:
torch.exp(k)

tensor([[4.4241e+05, 4.0343e+02, 5.4598e+01],
        [2.2026e+04, 5.9874e+04, 5.4598e+01]])

In [42]:
torch.sigmoid(k)

tensor([[1.0000, 0.9975, 0.9820],
        [1.0000, 1.0000, 0.9820]])

In [43]:
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0067, 0.5000],
        [0.0474, 0.9933, 0.5000]])

In [44]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.5740, 0.9233, 0.9178],
        [0.7590, 0.7775, 0.6179]])
tensor([[0.3379, 0.2170, 0.9454],
        [0.7116, 0.1157, 0.6574]])


## Inplace
- Inplace is operation like add a value and store this value in existing memory address not take extra new memory

In [45]:
m.add_(n)
m

tensor([[0.9118, 1.1403, 1.8632],
        [1.4706, 0.8933, 1.2752]])

## **cloning the tensor**

In [46]:
p = m.clone()
p

tensor([[0.9118, 1.1403, 1.8632],
        [1.4706, 0.8933, 1.2752]])

## ***Tensor Operations in GPU***

In [47]:
device = torch.device('cuda')
device

device(type='cuda')

In [48]:
torch.rand((5, 5), device=device)

tensor([[0.3563, 0.0303, 0.7088, 0.2009, 0.0224],
        [0.9896, 0.3737, 0.0823, 0.2851, 0.4433],
        [0.2989, 0.4175, 0.2687, 0.0927, 0.2317],
        [0.9207, 0.1794, 0.8246, 0.7332, 0.8699],
        [0.5887, 0.0160, 0.9177, 0.5260, 0.4950]], device='cuda:0')

In [49]:
new_tensor = torch.ones(4, 4)
new_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [50]:
new_tensor.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [51]:
new_tensor.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
p = torch.rand(2, 3, 4)
p

tensor([[[0.3451, 0.0453, 0.9798, 0.5548],
         [0.6868, 0.4920, 0.0748, 0.9605],
         [0.3271, 0.0103, 0.9516, 0.2855]],

        [[0.2324, 0.9141, 0.7668, 0.1659],
         [0.4393, 0.2243, 0.8935, 0.0497],
         [0.1780, 0.3011, 0.1893, 0.9186]]])

In [53]:
p.permute(2, 0, 1)

tensor([[[0.3451, 0.6868, 0.3271],
         [0.2324, 0.4393, 0.1780]],

        [[0.0453, 0.4920, 0.0103],
         [0.9141, 0.2243, 0.3011]],

        [[0.9798, 0.0748, 0.9516],
         [0.7668, 0.8935, 0.1893]],

        [[0.5548, 0.9605, 0.2855],
         [0.1659, 0.0497, 0.9186]]])

In [54]:
print("Tst line")

Tst line
