## **Pytorch Tensor**

In [19]:
import torch

In [20]:
print('tst line')

tst line


In [21]:
if torch.cuda.is_available():
    print("GPU is avilable")
    print(f"Using GPU: {torch.cuda.get_device_name(0)} ")
else:
    print("GPU not avilable")

GPU is avilable
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU 


## **Creating a Tenson**

In [22]:
## It's creating a tensor and showing the existing value of that memory.
empt_tensor = torch.empty(2, 3)
empt_tensor

tensor([[2.3578e-11, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [23]:
type(empt_tensor)

torch.Tensor

In [24]:
## creating tensor using zero value
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [25]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [26]:
## To get the same tensor into the differents times
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [27]:
torch.ones(4)

tensor([1., 1., 1., 1.])

## **Build my own custome Tensor**

In [28]:
torch.tensor(
    [
        [1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]
    ]
)

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [29]:
torch.arange(4, 10)

tensor([4, 5, 6, 7, 8, 9])

## **Identity matrix**

In [30]:
torch.eye(4, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [31]:
## matrix using specific numbers.
torch.full((3, 4), 8)

tensor([[8, 8, 8, 8],
        [8, 8, 8, 8],
        [8, 8, 8, 8]])

## **Tensor Shapes Finding**

In [32]:
x = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [8, 9, 10]
    ]
)

In [33]:
x.shape

torch.Size([3, 3])

In [34]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

## **Finding Tensor data types**

In [38]:
my_tensor = torch.tensor(
    [
        [1, 2, 3],
        [2, 3, 4]
    ]
)
my_tensor

tensor([[1, 2, 3],
        [2, 3, 4]])

In [39]:
my_tensor.dtype

torch.int64

In [40]:
my_tensor_int_16 = torch.tensor(
    [
        [1, 2, 3],
        [2, 3, 4]
    ],
    dtype = torch.int16
)
my_tensor_int_16.dtype

torch.int16

## Transfer one datatype to desier data type `.to` 

In [41]:
flot_data = my_tensor_int_16.to(torch.float64)
flot_data

tensor([[1., 2., 3.],
        [2., 3., 4.]], dtype=torch.float64)

In [ ]:
## 