In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
X, y = make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [3]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [4]:
X = torch.tensor(X, dtype=torch.float64)
y = torch.tensor(y, dtype=torch.long)

In [5]:
X, y

(tensor([[ 1.0683, -0.9701],
         [-1.1402, -0.8388],
         [-2.8954,  1.9769],
         [-0.7206, -0.9606],
         [-1.9629, -0.9923],
         [-0.9382, -0.5430],
         [ 1.7273, -1.1858],
         [ 1.7774,  1.5116],
         [ 1.8997,  0.8344],
         [-0.5872, -1.9717]], dtype=torch.float64),
 tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0]))

## **Start of job Dataset and Dataloader class**

In [6]:
X.shape[0]

10

In [7]:
from torch.utils.data import Dataset, DataLoader

In [23]:
class MyCustomDatasetClass(Dataset):

    def __init__(self, features, labels):
        ## data loading is here.
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, index):
        ## apply data transforms here.
        return self.features[index], self.labels[index]

In [10]:
dataset = MyCustomDatasetClass(X, y)

In [12]:
len(dataset)

10

In [13]:
dataset[0]

(tensor([ 1.0683, -0.9701], dtype=torch.float64), tensor(1))

## **Dataloader using Dataset class**

In [21]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [22]:
for batch_features, batch_labels in dataloader:
    print(f"Batch Features: {batch_features} and labels {batch_labels} ")
    print("="*75)

Batch Features: tensor([[ 1.8997,  0.8344],
        [-0.9382, -0.5430]], dtype=torch.float64) and labels tensor([1, 1]) 
Batch Features: tensor([[ 1.7774,  1.5116],
        [-1.9629, -0.9923]], dtype=torch.float64) and labels tensor([1, 0]) 
Batch Features: tensor([[ 1.0683, -0.9701],
        [ 1.7273, -1.1858]], dtype=torch.float64) and labels tensor([1, 1]) 
Batch Features: tensor([[-0.7206, -0.9606],
        [-0.5872, -1.9717]], dtype=torch.float64) and labels tensor([0, 0]) 
Batch Features: tensor([[-2.8954,  1.9769],
        [-1.1402, -0.8388]], dtype=torch.float64) and labels tensor([0, 0]) 


## **Data Parallizations**
- using `worker` can be parralizations

In [30]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True, num_workers=2, pin_memory=True, drop_last=False)

In [29]:
for batch_features, batch_labels in dataloader:
    print(f"Batch Features: {batch_features} and labels {batch_labels} ")
    print("="*75)

Batch Features: tensor([[-0.7206, -0.9606],
        [ 1.7774,  1.5116]], dtype=torch.float64) and labels tensor([0, 1]) 
Batch Features: tensor([[ 1.0683, -0.9701],
        [-2.8954,  1.9769]], dtype=torch.float64) and labels tensor([1, 0]) 
Batch Features: tensor([[-1.9629, -0.9923],
        [-0.5872, -1.9717]], dtype=torch.float64) and labels tensor([0, 0]) 
Batch Features: tensor([[ 1.7273, -1.1858],
        [-0.9382, -0.5430]], dtype=torch.float64) and labels tensor([1, 1]) 
Batch Features: tensor([[ 1.8997,  0.8344],
        [-1.1402, -0.8388]], dtype=torch.float64) and labels tensor([1, 0]) 
